import { Link } from "react-router-dom";
import { Logo } from "../components/layout/Logo.jsx";
import { Button } from "../components/ui/Button.jsx";

const lastUpdated = "June 4, 2026";

const privacySections = [
  {
    title: "Information We Collect",
    body: [
      "OccuBoard collects account information you provide, including your name, email address, location, target roles, and profile settings.",
      "We collect resume uploads, extracted resume text, job descriptions, application records, generated materials, notes, contacts, interview prep content, and related activity you choose to save in the product.",
    ],
  },
  {
    title: "How We Use Your Information",
    body: [
      "We use your information to provide job analysis, resume tailoring, recruiter message drafting, interview preparation, application tracking, account management, billing, support, security, and product improvement.",
      "Your resume text and job descriptions are used to generate role-specific outputs and organize your job search workspace.",
    ],
  },
  {
    title: "AI Processing",
    body: [
      "OccuBoard uses OpenAI to process resume content, job descriptions, profile details, and application context when you request AI-powered analysis or generated materials.",
      "AI-generated outputs may be inaccurate or incomplete. You are responsible for reviewing, editing, and approving any content before using it.",
    ],
  },
  {
    title: "Service Providers",
    body: [
      "We use Stripe for subscription billing and payment processing. OccuBoard does not store full payment card numbers.",
      "We use Supabase for authentication, database storage, and file-related application data. We use Vercel for hosting and deployment infrastructure.",
    ],
  },
  {
    title: "Data Storage and Security",
    body: [
      "We use reasonable technical and organizational measures to protect your information. No internet-based service can be guaranteed to be perfectly secure.",
      "Your account data, resume text, job descriptions, and application tracking data are stored so the product can maintain your workspace across sessions.",
    ],
  },
  {
    title: "Your Rights and Data Deletion",
    body: [
      "You may request access, correction, export, or deletion of your personal information by contacting us.",
      "You can ask us to delete your account and associated workspace data, subject to legal, security, billing, or operational retention requirements.",
    ],
  },
  {
    title: "Contact",
    body: ["Questions about this Privacy Policy can be sent to support@occuboard.io."],
  },
];

const termsSections = [
  {
    title: "OccuBoard Services",
    body: [
      "OccuBoard is a job search operating system that helps users analyze opportunities, tailor resumes, draft recruiter messages, prepare for interviews, export application materials, and track applications.",
      "You are responsible for the accuracy of the information you enter and for deciding how to use any materials generated by the service.",
    ],
  },
  {
    title: "Subscriptions and Billing",
    body: [
      "OccuBoard may offer free usage limits and paid subscriptions. Paid subscriptions are billed through Stripe according to the price and billing interval shown at checkout.",
      "Subscriptions may be cancelled anytime through the billing portal. Cancellation stops future renewal charges but does not automatically refund past charges unless required by law or expressly stated.",
    ],
  },
  {
    title: "AI-Generated Content",
    body: [
      "OccuBoard uses AI to generate analysis, resume suggestions, cover letters, recruiter messages, interview preparation, and related materials.",
      "AI-generated content may contain errors, omissions, or wording that needs adjustment. You must review and approve all generated content before submitting it to employers, recruiters, or third parties.",
    ],
  },
  {
    title: "No Employment Guarantee",
    body: [
      "OccuBoard does not guarantee job interviews, job offers, hiring outcomes, recruiter responses, salary increases, or employment results.",
      "The service provides organization, drafting, analysis, and preparation tools. Hiring decisions are made by employers and other third parties outside OccuBoard's control.",
    ],
  },
  {
    title: "Acceptable Use",
    body: [
      "You agree not to use OccuBoard for unlawful, harmful, deceptive, abusive, infringing, or fraudulent activity.",
      "You may not upload content you do not have the right to use, attempt to disrupt the service, reverse engineer the platform, abuse usage limits, or use generated content to misrepresent your experience or qualifications.",
    ],
  },
  {
    title: "Account Responsibility",
    body: [
      "You are responsible for maintaining the confidentiality of your account credentials and for activity under your account.",
      "Notify us if you believe your account has been accessed without authorization.",
    ],
  },
  {
    title: "Limitation of Liability",
    body: [
      "To the maximum extent permitted by law, OccuBoard and its operators are not liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, lost opportunities, lost data, or employment-related outcomes.",
      "OccuBoard is provided on an as-is and as-available basis, subject to applicable law.",
    ],
  },
  {
    title: "Contact",
    body: ["Questions about these Terms can be sent to support@occuboard.io."],
  },
];

export function PrivacyPage() {
  return <LegalDocument title="Privacy Policy" intro="This Privacy Policy explains how OccuBoard collects, uses, stores, and protects information when you use the service." sections={privacySections} />;
}

export function TermsPage() {
  return <LegalDocument title="Terms of Service" intro="These Terms of Service describe the rules and responsibilities that apply when you use OccuBoard." sections={termsSections} />;
}

function LegalDocument({ title, intro, sections }) {
  return (
    <div className="min-h-screen bg-[#fbfaf8] text-ink">
      <header className="border-b border-brand-100 bg-white/95">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-5 sm:px-6">
          <Link to="/" aria-label="OccuBoard home"><Logo /></Link>
          <Link to="/signup"><Button className="min-h-9 px-3">Get Started</Button></Link>
        </div>
      </header>
      <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14">
        <section className="rounded-xl border border-brand-100 bg-white p-5 shadow-card sm:p-8">
          <p className="text-xs font-black uppercase tracking-[0.16em] text-brand-600">OccuBoard</p>
          <h1 className="mt-2 text-4xl font-black tracking-normal text-ink">{title}</h1>
          <p className="mt-3 text-sm font-semibold text-slate-500">Last Updated: {lastUpdated}</p>
          <p className="mt-5 max-w-3xl text-base leading-7 text-slate-700">{intro}</p>
        </section>
        <section className="mt-6 grid gap-4">
          {sections.map((section) => (
            <article key={section.title} className="rounded-xl border border-slate-200/70 bg-white p-5 shadow-sm">
              <h2 className="text-xl font-black text-ink">{section.title}</h2>
              <div className="mt-3 grid gap-3 text-sm leading-7 text-slate-700">
                {section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
              </div>
            </article>
          ))}
        </section>
      </main>
      <PublicFooter />
    </div>
  );
}

export function PublicFooter() {
  return (
    <footer className="border-t border-brand-100 bg-white px-4 py-6 text-sm text-slate-600">
      <div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <p className="font-semibold">© {new Date().getFullYear()} OccuBoard</p>
        <nav className="flex flex-wrap gap-4" aria-label="Legal links">
          <Link className="font-semibold hover:text-brand-800" to="/privacy">Privacy Policy</Link>
          <Link className="font-semibold hover:text-brand-800" to="/terms">Terms of Service</Link>
        </nav>
      </div>
    </footer>
  );
}
